### ISSUE TITLE
Lockable Pressure Plates

### ISSUE THREAD

**Issue by ReeceTD** [commandgeek/geeksmp#1]
### What and How?

Within the GeekSMP, there is Lockable Blocks such as chests, buttons, levers etc...

We would love for lockable pressure plates to be added, also.

### Why?

Lockable pressure plates fits well within the server and the currently lockable, and would make it so you can have all types of redstone doors without having to add extra mechanics to lock and unlock your doors.

### Are there alternatives?

No alternative to this.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by commandgeek** [comment]
FYI someone in the code there is a list of blocks that can be locked. Adding more blocks should just be as simple as adding that block to the list.
