### ISSUE TITLE
Permanent pvp bar

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#106]
### Expected behavior

After the 10 seconds of the pvp bar, it will go away. This branches off of the previous bug I report about 2 pvp bars. After you get two, one will often stay. 

### Actual behavior

One bar will stay. 

### Steps to reproduce

Get the 2 bar thing to occur (do not know a very reliable method to get it to work yet) and wait for the time to run out. 

### Minecraft version and OS

1.18.1 windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

![56AA7858-0F49-4DF8-8D28-C033527243DF](https://user-images.githubusercontent.com/98910373/155829602-7fa64696-7b6a-456e-934d-5f9a83838dfd.jpeg)
I haven’t done any pvp for about half an hour but this is still there.

**Comment by srnyx** [comment]
Just add this onto your previous issue as they're related please.
