### ISSUE TITLE
/home

### ISSUE THREAD

**Issue by OlivierMolen** [commandgeek/geeksmp#111]
### What and How?

a command to set a home and a command so you can easy travel to your home

### Why?

for easier travel, so reece can learn better coding

### Are there alternatives?

/back

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by techred32** [comment]
As much as I like this idea it seems kinda over powered. Let’s say you are burning in lava in the nether for example and you don’t have anything to escape. You would be able to /home out of the situation.

**Comment by techred32** [comment]
> > As much as I like this idea it seems kinda over powered. Let’s say you are burning in lava in the nether for example and you don’t have anything to escape. You would be able to /home out of the situation.
> 
> i might have forgotten to put in the comment that there should be something in it like the combatlog. So by accemple you need to not have taken any damage in the last 10 seconds. and that counts for players and survival damage.

Yeah that would make a lot more sense. It seems a bit chesty to me but I do like it.

**Comment by srnyx** [comment]
No
