### ISSUE TITLE
Disguise!

### ISSUE THREAD

**Issue by FlyingDrag0n** [commandgeek/geeksmp#112]
### What and How?

Disguise for staff!

To catch hackers/xrayers/etc or wanna play weird.

Admins or mods can use /disguise to transform into a mob or random player. 
This might sound dumb. But hackers feel comforable of doing hacks when they don't see staff/mods in tab as invisable. 

So Staff can use /disguise or /customname [Name] to spy on them as a normal defealt undead/player.

They can also do this to be a pig, I guess

### Why?

In TAB, you can see when staff they're in vanish or when they're on to someone.

This can be the best oppurtunity to catch someone without them noticing.

And also good for some weird lores I guess.

### Are there alternatives?

No.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Add a candy van entity.

**Comment by techred32** [comment]
They have vanish. It’s more reasonable to use vanish.

**Comment by techred32** [comment]
> They have vanish. It’s more reasonable to use vanish.

Also, you can’t see staff in vanish. You can see them in spectator, not vanish.

**Comment by srnyx** [comment]
We can just use `/vanish`
