### ISSUE TITLE
A way to see the nether roof on the map

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#113]
### What and How?

There could be an option on the map website to see nether roof. 

### Why?

It would be nice when lookin for players as undeads, if there is a farm on roof you can see, and player is in that place ont he roof, you know where they are. Also it just feels like a missing feature right now. 

### Are there alternatives?

There is, we don’t add it. Another would be for undeads to just go to the location using /track and if the player is above them (they can check by jumping and seeing if the track number goes down) and then go back and go to same spot on the roof. 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

I have no clue if this is even possible

**Comment by srnyx** [comment]
**Done!**
Select the 3rd map for `Nether`:
![image](https://user-images.githubusercontent.com/25808801/156908785-f17ab98c-544e-48ee-bcc3-36afe98cef32.png)
