### ISSUE TITLE
New Bad Omen potions

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#118]
### What and How?

It would be like any other potion but when you drink it you get the bad omen effect for a limited time. 

Obviously the potion should be slightly costly. Maybe it would need a crossbow or a bottle enchanting since outposts have that material in their chests. 

### Why?

The Terra generation plugin changed outposts which causes and issue where the pillagers don’t spawn near the outpost, spawn in a random area far away, or don’t spawn at all. This could be a good alternative way of getting bad omen. 

### Are there alternatives?

I mean you could go to pillager outposts and try to find where in the world the pillagers are spawning or if they aren’t spawning at all. 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
> I mean you could go to pillager outposts and try to find where in the world the pillagers are spawning or if they aren’t spawning at all.

They don't spawn at all (or maybe they just spawn once but after that they don't respawn)

**Comment by techred32** [comment]
> > I mean you could go to pillager outposts and try to find where in the world the pillagers are spawning or if they aren’t spawning at all.
> 
> They don't spawn at all (or maybe they just spawn once but after that they don't respawn)

Exactly why this potion should exist B)
