### ISSUE TITLE
Undeads can glide with elytra

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#123]
### Expected behavior

Undeads shouldn’t be able to use elytra for flying or gliding at all. 

### Actual behavior

Undeads cannot fly but they can glide (they will take damage upon landing though)

### Steps to reproduce

I really don’t know, I became aware of this through someone mentioning it in discord. 
I assume either
1. Be undead
2. Equip elytra
3. Jump from height and click space to glide as normal

Or
1. Be undead
2. Equip elytra
3. Jump from height and spam click space to glide

### Minecraft version and OS

Dan (the guy who informed me of this) plays on 1.18.2 Lunar on Mac

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

And I think a way of fixing this is just to prevent Undeads from equipping elytra

**Comment by srnyx** [comment]
Gliding is fine, using fireworks isn't though.
