### ISSUE TITLE
Undeads not being able to use Elytras

### ISSUE THREAD

**Issue by ReeceTD** [commandgeek/geeksmp#16]
### What and How?

Undeads should not be able to use elytras, to removing the ability for their Armor chestplate slot to be filled with an elytra should be revoked.

### Why?

A Few Reasons

- The Elytra animation does not work on undead players
- They can easily escape, glitch and cause havoc with this item semi-legally, when this shouldn't be an open possibility for them.

### Are there alternatives?

Not necessarily alternatives, but if you can fix the reasons why they shouldn't be able to use elytras, then do that.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by DWAA1660** [comment]
So you want undeads to be unable to wear elytras

**Comment by srnyx** [comment]
> So you want undeads to be unable to wear elytras?

Either not be able to wear or not be able to use. I guess whichever is easier.
