### ISSUE TITLE
Gradle workflows don't work

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#21]
### Expected behavior

The workflow should be able to build the plugin jar automatically for every new commit made in `master` branch and pull requests.

### Actual behavior

It fails because it requires Build Tools.

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

I don't want to require/use Build Tools.
This can be done by replacing anything that imports `net.minecraft` with something like [Protocol Library](https://www.spigotmc.org/resources/1997).

**Comment by Lianecx** [comment]
#38
