### ISSUE TITLE
Discord chat to Minecraft chat

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#26]
### What and How?

Messages sent in `#smp-chat` should be sent into Minecraft.

### Why?

So players that aren't currently in-game can speak to ones in-game.

### Are there alternatives?

Pinging the people in-game and talking in `#public` (inefficient and they may not see the ping).

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by commandgeek** [comment]
For anyone dealing with this issue. Currently, any messages sent in #smp-chat by an administrator will be sent to the GeekSMP console as a command. If this is replaced with Discord-to-Minecraft chatting, we must still implement a way to run console commands (by admins) through #smp-chat. Perhaps this could be accomplished by beginning the message with "/".
