### ISSUE TITLE
Remove ability to lock ender chests

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#29]
### What and How?

Don't allow ender chests to be locked using the lock tool

### Why?

There is no point in locking ender chests.

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by DWAA1660** [comment]
people can break the echest for obby i guess that's griefing but still

**Comment by srnyx** [comment]
> people can break the echest for obby i guess that's griefing but still

You can break anything that can't be locked (like netherite blocks, diamond blocks, etc...)... so...
