### ISSUE TITLE
Undead Morph Broken

### ISSUE THREAD

**Issue by ReeceTD** [commandgeek/geeksmp#34]
### Expected behavior

When an undead disconnects from the server, their morph should go with them.

### Actual behavior

In some very rare circumstances [only know of 2], skeleton morphs have remained frozen in place permanently, even when the user controlling the morph disconnects.
You cannot kill, destroy, move or do anything with these frozen morphs/undeads.

 ![image](https://user-images.githubusercontent.com/98226198/151717761-e13ba184-80de-4510-8a5a-7e36babf9840.png)

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by DWAA1660** [comment]
i reproduced a couple times it seems to happen when an undead is on the server and the chunks suddenly unload or server shuts down

**Comment by srnyx** [comment]
This was sorta fixed. Just had to clear the `morphs.yml` data file!
