### ISSUE TITLE
Command to toggle lock bypass

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#36]
### What and How?

A command to bypass locked stuff (`/bypass`).

### Why?

Shift-right clicking to bypass is fine, but it has some issues, and if you're frequently bypassing there isn't much of a point in requiring you to do it.

### Are there alternatives?

Shift-right clicking

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by DWAA1660** [comment]
would having so staff automaticly bypass work?

**Comment by srnyx** [comment]
> would having so staff automaticly bypass work?

A command to toggle bypassing would be better as CommandGeek (or other staff) probably doesn't accidentally steal from someone.

**Comment by Lianecx** [comment]
What does this mean? That Staff is able to look in locked chests using that command?

**Comment by srnyx** [comment]
> What does this mean? That Staff is able to look in locked chests using that command?

Yes, and use locked levers/buttons/etc... We can already do this by crouching and right-clicking. But it doesn't work if something is your hand or offhand, so it's really annoying.

**Comment by Lianecx** [comment]
So fixing that would also be fine?

**Comment by srnyx** [comment]
> So fixing that would also be fine?

No, I'd prefer a command so that I don't have to crouch at all.
