### ISSUE TITLE
Skeleton undeads can farm arrows/bows

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#37]
### Expected behavior

- Skeleton bows/arrow shouldn't be dropped on death.
- Arrows shouldn't be able to be picked up from skeleton undead's bow shots

### Actual behavior

- Skeleton bows/arrow drop on each death
- Arrows can be picked up if it's stuck in the ground when shot by a skeleton undead

### Steps to reproduce

-
1. Become skeleton undead
2. Die
3. Go to death location
4. Pick up bow

-
1. Become skeleton undead
2. Shoot an arrow
3. Pick up arrow

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by DWAA1660** [comment]
you can make the bow have infinity idk where this is handled so i cant do it

**Comment by srnyx** [comment]
> you can make the bow have infinity idk where this is handled so i cant do it

https://github.com/commandgeek/geeksmp/blob/master/src/main/java/com/commandgeek/GeekSMP/Morph.java#L58

**Comment by Lianecx** [comment]
Should the arrows be deleted or just not pickable?

**Comment by commandgeek** [comment]
FYI I did add a piece of code that prevents the undead player themselves from picking up the arrows. I didn't think about revived players using undead to farm arrows, however.

**Comment by srnyx** [comment]
They can still farm as when they die they drop a bow/arrow.
