### ISSUE TITLE
Some words are not blacklisted in-game

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#4]
### Expected behavior

Any and all inappropriate language should be blacklisted.

### Actual behavior

Some words aren't properly blacklisted or easily bypassable.

### Steps to reproduce

N/A

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by DWAA1660** [comment]
i gave reece a list you can add to your comfig.yml then you can close this issue since its a config problem
