### ISSUE TITLE
Incorrect username formatting in #smp-chat

### ISSUE THREAD

**Issue by commandgeek** [commandgeek/geeksmp#41]
### Expected behavior

Names containing underscores or other special characters should not be formatted in the discord message.

### Actual behavior

Names with underscores or other special characters in some cases are formatted in the discord message. Attached is an example.
<img width="184" alt="Screenshot 2022-02-01 at 14 07 12" src="https://user-images.githubusercontent.com/98085859/151973921-9a9365cb-0911-4138-98e5-1deeda6e9f30.png">

### Steps to reproduce

Have anyone with underscores in their name (aka Bag_of_Doritos) join, leave, or chat in the server and observe #smp-chat.

### Minecraft version and OS

N/A

### Checks

- [ ] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by srnyx** [comment]
This can be fixed by putting a `\\` before formatting characters

**Comment by Lianecx** [comment]
Exactly

**Comment by srnyx** [comment]
This is still happening: 
![image](https://user-images.githubusercontent.com/25808801/153770412-eaa4aa68-cb20-4c60-be76-b754da1261dc.png)

**Comment by Lianecx** [comment]
No idea why

**Comment by Lianecx** [comment]
Ooof, i think i know why:
Replace the replace method in MessageManager (the second one with three parameters) with this:

```MessageManager replace(String regex, String replacement, boolean escapeMarkdown) {

        message = message.replaceAll(regex, replacement);

        if(escapeMarkdown) {
            String mdRegex = "[*_`~>|]";
            replacement = replacement.replaceAll(mdRegex, Matcher.quoteReplacement("\\")+"$0");
        }

        return this;
    } ```

**Comment by srnyx** [comment]
> Replace the replace method in MessageManager (the second one with three parameters)

This one?
```java
    public MessageManager replace(String regex, String replacement) {
        message = message.replaceAll(regex, replacement);
        return this;
    }
```

**Comment by Lianecx** [comment]
Read my message: the second one woth THREE parameters

**Comment by srnyx** [comment]
> Read my message: the second one woth THREE parameters

![image](https://user-images.githubusercontent.com/25808801/153771576-12df56cf-724c-4b74-b661-5cc21aaf2989.png)

**Comment by Lianecx** [comment]
Yes but wait a second i dont think that will cjange anything
