### ISSUE TITLE
MC username -> Discord nickname

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#43]
### What and How?

Change players’ Discord nicknames to their Minecraft username.

### Why?

This will make it so that it’s easier to see who someone is in Minecraft.

### Are there alternatives?

Requiring people to change their nickname to their Minecraft username or manually changing them ourselves.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Lianecx** [comment]
Isnt this already done?

**Comment by Lianecx** [comment]
Pretty sure the plugin already nicknames all verified people

**Comment by srnyx** [comment]
> Pretty sure the plugin already nicknames all verified people

Oops
