### ISSUE TITLE
Iron golems and undeads

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#48]
### Expected behavior

Since undeads are either zombies or skeletons iron golems should move towards and damage them like when a player hits a golem. 

### Actual behavior

Iron golems go to the undead and attack, but it doesn’t do any damage. 

### Steps to reproduce

1. Be undead
2. Stand around iron golem
3. Observe

### Minecraft version and OS

Server version

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

https://media.discordapp.net/attachments/882211454437179392/923390026790875146/unknown.png

**Comment by techred32** [comment]
Datnip told me that the golems were supposed to do damage but he was unsure.

**Comment by MillkSheik** [comment]
i think the iron golems try attacking the morph instead of the player or something like that
