### ISSUE TITLE
Effect disappeares upon relog 

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#51]
### Expected behavior

When you leave and rejoin you keep the potion effects you had before you left. 

### Actual behavior

When you relog you lose the effect(s) you had before you left. 

### Steps to reproduce

1. Have an effect
2. Disconnect
3. Reconnect
4. Effect gone

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

I found this while trying to start a raid. I got bad omen from Biancas house and was going to the place I wanted to do the raid. I had to disconnect for a minute and when I rejoined I realized I did not have bad omen anymore. I asked in the discord and Datnip verified this is a bug.

**Comment by srnyx** [comment]
> Server version

This is not an appropriate answer

**Comment by DWAA1660** [comment]
> > Server version
> 
> This is not an appropriate answer

it works in all versions of the server

**Comment by srnyx** [comment]
> > > Server version
> > 
> > 
> > This is not an appropriate answer
> 
> it works in all versions of the server

??????????

**Comment by DWAA1660** [comment]
> > > > Server version
> > > 
> > > 
> > > This is not an appropriate answer
> > 
> > 
> > it works in all versions of the server
> 
> ?????????? That field is for your Minecraft client version and Operating System. I have no idea what "server version" is supposed to mean or what "all versions of the server" is.

You can gues all versions that you can join geek smp on it works ex. 1.18.1 1.17.1 1.18 etc

**Comment by srnyx** [comment]
> You can gues all versions that you can join geek smp on it works ex. 1.18.1 1.17.1 1.18 etc

That's exactly why the field exists. Some issues may only be present when the client is on a different version than the server. Putting "server version" doesn't tell us anything.

**Comment by srnyx** [comment]
Confirmed. Happens to both alive and undead.
