### ISSUE TITLE
Sweeping damage also hurts undeads

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#52]
### Expected behavior

If you're an undead at an enderman farm and you use a sweeping edge sword the endermen will take sweeping damage and you will be fine.

### Actual behavior

If you're an undead at an enderman farm and you use a sweeping edge sword the endermen **and yourself** will take sweeping damage.

### Steps to reproduce

1. Be undead
2. Go to a farm where many mobs go in one place for you to sweep like the enderman farm
3. Go up to the endermen and use your sword
4. See that you take damage

https://youtube.com/watch?v=NySyuWdGu2k

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by srnyx** [comment]
> Server version

This is not an appropriate answer

**Comment by techred32** [comment]
> > Server version
> 
> This is not an appropriate answer

Sorry, I don't know what version the server is and I know it is an issue in the server.

**Comment by srnyx** [comment]
> > > Server version
> > 
> > 
> > This is not an appropriate answer
> 
> Sorry, I don't know what version the server is and I know it is an issue in the server.

What...? Why would you need to know the server version...???

**Comment by techred32** [comment]
> > Sorry, I don't know what version the server is and I know it is an issue in the server.
> 
> What...? Why would you need to know the server version...???

I thought I needed to include the version.

**Comment by Lianecx** [comment]
This has been fixed in #82 i think. I do not experience any issues at the farm anymore
