### ISSUE TITLE
Riptide does not work right with undeads

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#54]
### Expected behavior

When using riptide as undead it will work just like normal, as it would with an alive.

### Actual behavior

The undead player takes damage from the trident mid-air stopping the riptide.

### Steps to reproduce

1. Be undead
2. Have Riptide trident
3. Use riptide trident mid air
4. Observer that you take damage mid air and fall

https://youtu.be/RKE3HBLtves

### Minecraft version and OS

1.17.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

_No reponse_

**Comment by srnyx** [comment]
> ### Minecraft version and OS
> 1.17.1

You need to include your OS too...

**Comment by techred32** [comment]
> > ### Minecraft version and OS
> > 1.17.1
> 
> You need to include your OS too...

Windows 10
