### ISSUE TITLE
Make player invulnerable when AFK

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#56]
### What and How?

When a user is AFK make it so they can't take damage from mobs/players.

### Why?

If you suddenly have to go AFK an undead, another alive player, or mobs can come and kill you. Then your stuff will despawn or be taken.

### Are there alternatives?

Leaving the server instead of going AFK.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by DWAA1660** [comment]
i suggested this but there would have to be a way to prevent "combat afking"

**Comment by srnyx** [comment]
> i suggested this but there would have to be a way to prevent "combat afking"

https://github.com/commandgeek/geeksmp/issues/5

**Comment by Lianecx** [comment]
> i suggested this but there would have to be a way to prevent "combat afking"

Combat logging is allowed

**Comment by Lianecx** [comment]
Doesnt really make a difference if you do it with /afk or leaving

**Comment by srnyx** [comment]
> > i suggested this but there would have to be a way to prevent "combat afking"
> 
> Combat logging is allowed

We don't want it allowed. But we can't really prevent it as it's hard to define "combat logging" (without a system to do it for you).
That's why https://github.com/commandgeek/geeksmp/issues/5 exists...
