### ISSUE TITLE
Command to give Lock Tool

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#59]
### What and How?

A command that will give the player that used it.
`/locktool give [player]` (`[player]` is optional, if not specified it will give to the person that used it)

### Why?

When testing, it's really annoying to make a Lock Tool by getting a crafting table, Amethyst Shard, and 2 Sticks.

### Are there alternatives?

Not really, no

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by DWAA1660** [comment]
alternative is using saved hotbars but yea

**Comment by srnyx** [comment]
> alternative is using saved hotbars but yea

Saved hotbars would overwrite the current hotbar and don't allow for other players. But yeah I guess it could be.
