### ISSUE TITLE
Undeads can easily switch morphs

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#71]
### Expected behavior

Undeads shouldn't be able to rechoose their morph upon relogging.

### Actual behavior

Undeads can combat log by relogging which makes them go into the morph selection screen. This also lets them easily switch morphs in the middle of a battle (need range, switch to skeleton. Close quarters, use zombie).

### Steps to reproduce

1. Be undead
2. Log out
3. Log in
4. You can rechoose your morph

### Minecraft version and OS

1.18.1, Windows 10

### Checks

- [X] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Lianecx** [comment]
This has been fixed (combat log plugin has been added)

**Comment by srnyx** [comment]
> This has been fixed (combat log plugin has been added)

No. They can still leave once combat has ended to easily switch morphs.

**Comment by Lianecx** [comment]
They should be able to switch morphs after combat has ended
