### ISSUE TITLE
Blacklisted Words - Format Code K

### ISSUE THREAD

**Issue by ReeceTD** [commandgeek/geeksmp#8]
### What and How?

For blacklisted words such as curses, or slurs, have them covered automatically by format code `K` in-game instead of `*****`

### Why?

There is no specific reason for this, it just makes things look easier, and makes it easier for staff to identify swears and not people just spamming `****` for no reason in particular.

![java_pZzWrWpbTR](https://user-images.githubusercontent.com/98226198/151637916-f613165e-8117-4ad0-aa50-a01af110ed36.png)

### Are there alternatives?

I do not know of any other alternative to this, that would cover it nicely and be easily identifiable as a swear by staff. 
Feel free to create something different.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Lianecx** [comment]
How would it be displayed in discord though?

**Comment by srnyx** [comment]
> How would it be displayed in discord though?

You can just use asterisks (same as current)
