### ISSUE TITLE
Only tab complete banned players for `/unban`

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#81]
### What and How?

Only show tab completion for currently banned players when doing `/unban`

### Why?

There is no point in tab completing every player (online & offline) if using the command on 99% of them won't do anything.

### Are there alternatives?

- Ignore it
- Only tab-complete online

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Lianecx** [comment]
It already tab completes only the banned players

**Comment by Lianecx** [comment]
It worked completely fine for me, only the unbanned players were showing up in the tab complete

**Comment by srnyx** [comment]
> It already tab completes only the banned players

My bad, I guess we just have a lot of people banned lol
