### ISSUE TITLE
Skeletons should get arrows faster 

### ISSUE THREAD

**Issue by DWAA1660** [commandgeek/geeksmp#87]
### Expected behavior

Immediately after shooting they should get another arrow so then can spam them

### Actual behavior

Once you shoot you have to wait a second to get an arrow allowing people to catch up and compared to zombie skeletons are extremely debuffed and this would help even it out

### Steps to reproduce

Become an undead become a skeleton shoot an arrrow

### Minecraft version and OS

1.17.1

### Checks

- [ ] I am using modifications (mods, resourcepacks, etc...). (check if yes)
- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Lianecx** [comment]
This is intended

**Comment by DWAA1660** [comment]
> This could be "fixed" by making the bow have infinity (and curse of vanishing to kill two birds with stone: #37 [sorta, they could still be dropped and the arrows can still be farmable]). Then just only give the player an arrow once.

if you drip arrow it dont give you another one

**Comment by Lianecx** [comment]
It doesnt have to be infinity, the delay just has to be removed in the code. Curse of vanishing is a good idea

**Comment by Lianecx** [comment]
One arrow per death.

**Comment by Lianecx** [comment]
I wouldnt call that “farming”

**Comment by srnyx** [comment]
> It doesnt have to be infinity, the delay just has to be removed in the code. Curse of vanishing is a good idea

Arrows would still be farmable by dropping the arrows. That would just make them more easily farmable.

> One arrow per death. I wouldnt call that “farming”

It still makes them farmable. It doesn't matter how many they get, it's still considered farmable.

**Comment by Lianecx** [comment]
> > It doesnt have to be infinity, the delay just has to be removed in the code.
> 
> Arrows would still be farmable by dropping them. A smaller delay would just make them more easily farmable.

A smaller delay doesnt make it more farmable. If they drop theur arrow by pressing “q” they dont get a new one. And shot arrows cannot be picked up

**Comment by srnyx** [comment]
> > > It doesnt have to be infinity, the delay just has to be removed in the code.
> > 
> > 
> > Arrows would still be farmable by dropping them. A smaller delay would just make them more easily farmable.
> 
> A smaller delay doesnt make it more farmable. If they drop theur arrow by pressing “q” they dont get a new one. And shot arrows cannot be picked up

I still think infinity is the better, easier, and safer option.

**Comment by srnyx** [comment]
Closing this as #37 exists and the delay is intended.
