### ISSUE TITLE
Display rank in Discord chat

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#93]
### What and How?

Display the team prefix in the Discord channel when a player sends a message.
Example:
`OWNER CommandGeek » message`

### Why?

Just a nice touch

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Would probably be easier/best if https://github.com/commandgeek/geeksmp/issues/57 was done first.

**Comment by FlyingDrag0n** [comment]
Sounds good
