### ISSUE TITLE
`/trash`

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#95]
### What and How?

A `/trash` command that will open an empty "chest" GUI. When the GUI is closed, all the items placed inside of it are deleted.
Only usable by staff.

### Why?

Super useful to quickly get rid of items if we are restoring someone's inventory or something.

### Are there alternatives?

- Flint and steel
- Placing the items in the inventory restore GUI (does the same thing as `/trash` would)

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by FlyingDrag0n** [comment]
Or.. you can just click the red X in the inventory of the creative gamemode thing twice. Which auto delete your whole inventory(Make sure you don't have your own items lol)

And apart from that.. I find it rather useless.

**Comment by srnyx** [comment]
> Or.. you can just click the red X in the inventory of the creative gamemode thing twice. Which auto delete your whole inventory(Make sure you don't have your own items lol)
> 
> And apart from that.. I find it rather useless.

1. Annoying to switch from survival to creative and then back to survival
2. To make use of shift-clicking the X you'd have to empty all of your own items, then click on it, then pick up your items back up (without someone taking them)
3. If it's a lot of items then deleting them 1 by 1 via creative menu/X would take a long time (and you risk accidentally shift-clicking the X or something [very scary])

**Comment by Lianecx** [comment]
You can also just go to creative mode and shift-click your items into any tab of the creative inventory (except the survival inventory tab). That will delete them as well

**Comment by srnyx** [comment]
> You can also just go to creative mode and shift-click your items into any tab of the creative inventory (except the survival inventory tab). That will delete them as well

The items have to be in your hotbar. And I only have 2 empty slots when I have all my gear in my hotbar. So I'd either have to keep changing between inventory and creative tab and move each item into those 2 slots. Or I'd have to move all my survival items into my inventory and then all of the other items into my hotbar. But sometimes all of those items I wanna delete fill up my inventory, so it's really annoying to do.
So doing that would be the worst method. And besides, I've already made the command, wasn't hard at all.
