### ISSUE TITLE
Remember `/bypass`

### ISSUE THREAD

**Issue by srnyx** [commandgeek/geeksmp#96]
### What and How?

If `/bypass` is enabled, keep it enabled when user relogs.

### Why?

Annoying to redo the command every time we rejoin.

### Are there alternatives?

Another command, `/alwaysbypass` that will automatically enable bypass every time the user joins.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Lianecx** [comment]
Why do you have to have bypass enabled all the time. It should only be enabled for moderation in soecific situations

**Comment by srnyx** [comment]
> Why do you have to have bypass enabled all the time? It should only be enabled for moderation in soecific situations

Some staff may only be on the server to moderate (like I used to do).
Locking is also to prevent stealing, staff won't steal.
