### ISSUE TITLE
Lockable doors

### ISSUE THREAD

**Issue by techred32** [commandgeek/geeksmp#98]
### What and How?

Make it so that we can use the lock tool on all types of doors. This would prevent players from opening them. 

### Why?

This would be nice because some builds really need just one type of door. Currently, iron doors are the only doors that can keep undead players out if they do not have pearls, but iron doors often look bad on builds. We could not only keep some undeads out with any door of our liking but we could also lock certain areas to signify to some players “don’t go in there.”

### Are there alternatives?

We could stick to using iron doors. 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
I added trapdoors to the `lockable-blocks` list.
**Issue with doors:** When a door is locked, only the half that the player clicks on is actually locked. So the player would have to lock both the top and bottom half for it to work correctly.
